"""
Project Euler - Problem 16: Power Digit Sum
Answer: 1366
Resolved on Attempt: 1 in 0.0753s
Generated by Gemini AI Agent
"""

def solve():
    # Calculate 2^1000 and convert it to a string to easily iterate over its digits
    number_str = str(2**1000)
    
    # Sum the integer value of each character in the string
    digit_sum = sum(int(digit) for digit in number_str)
    
    print(digit_sum)

if __name__ == "__main__":
    solve()