"""
Project Euler - Problem 20: Factorial Digit Sum
Answer: 648
Resolved on Attempt: 1 in 0.0548s
Generated by Gemini AI Agent
"""

import math


def solve():
    # Calculate 100! using Python's built-in math.factorial,
    # which handles arbitrarily large integers efficiently.
    factorial_value = math.factorial(100)

    # Convert the number to a string, convert each character to an integer, and sum them.
    digit_sum = sum(int(char) for char in str(factorial_value))

    print(digit_sum)


if __name__ == "__main__":
    solve()