"""
Project Euler - Problem 9: Special Pythagorean Triplet
Answer: 31875000
Resolved on Attempt: 1 in 0.0642s
Generated by Gemini AI Agent
"""

def solve():
    target = 1000
    # We know that a < b < c and a + b + c = 1000.
    # Also, a^2 + b^2 = c^2.
    # Therefore, a < target / 3, roughly.
    # We can loop through possible values of a and b to find the triplet.
    
    for a in range(1, target // 3):
        # Since a + b + c = target and a < b < c, 
        # b must be greater than a and less than (target - a) / 2
        for b in range(a + 1, (target - a) // 2):
            c = target - a - b
            if a*a + b*b == c*c:
                return a * b * c

if __name__ == "__main__":
    print(solve())