"""
Project Euler - Problem 12: Highly Divisible Triangular Number
Answer: 76576500
Resolved on Attempt: 1 in 2.4112s
Generated by Gemini AI Agent
"""

def count_divisors(n):
    """Counts the number of divisors of an integer n efficiently."""
    count = 0
    limit = int(n**0.5)
    for i in range(1, limit + 1):
        if n % i == 0:
            count += 2  # i and n // i
    # If n is a square number, subtract 1 to avoid double counting the square root
    if limit * limit == n:
        count -= 1
    return count

def solve():
    n = 1
    triangle_number = 1
    while True:
        # The nth triangle number can be calculated as n * (n + 1) // 2
        # To optimize, we can use the property that gcd(n, n+1) = 1,
        # so the number of divisors of n*(n+1)/2 is the product of the number of divisors
        # of the reduced parts, or we can just count divisors of the triangle number directly
        # since computing divisors up to sqrt(76576500) is very fast.
        
        triangle_number = n * (n + 1) // 2
        
        if count_divisors(triangle_number) > 500:
            return triangle_number
        
        n += 1

if __name__ == "__main__":
    answer = solve()
    print(answer)