"""
Project Euler - Problem 10: Summation of Primes
Answer: 142913828922
Resolved on Attempt: 1 in 0.2154s
Generated by Gemini AI Agent
"""

def solve():
    limit = 2000000
    # Use the Sieve of Eratosthenes to find all primes below 2,000,000.
    # is_prime[i] will be True if i is prime, False otherwise.
    is_prime = [True] * limit
    is_prime[0] = is_prime[1] = False

    for p in range(2, int(limit**0.5) + 1):
        if is_prime[p]:
            # Mark multiples of p as not prime, starting from p^2
            is_prime[p * p : limit : p] = [False] * len(
                range(p * p, limit, p)
            )

    # Sum all numbers that are marked as prime
    prime_sum = sum(i for i, prime in enumerate(is_prime) if prime)

    print(prime_sum)


if __name__ == "__main__":
    solve()