"""
Project Euler - Problem 14: Longest Collatz Sequence
Answer: 837799
Resolved on Attempt: 1 in 1.6363s
Generated by Gemini AI Agent
"""

def solve():
    limit = 1_000_000
    # Memoization table to store chain lengths.
    # Using a list for fast indexing up to a certain point, but since numbers can exceed
    # 1 million during the sequence, a dictionary or a larger array can be used.
    # Actually, a dictionary `memo` is safe and efficient for arbitrary values,
    # but for numbers < limit, an array is faster. Let's use a dict with a base case.
    
    memo = {1: 1}

    def get_length(n):
        if n in memo:
            return memo[n]
        
        # Compute the next term in the Collatz sequence
        if n % 2 == 0:
            next_n = n // 2
        else:
            next_n = 3 * n + 1
            
        length = 1 + get_length(next_n)
        memo[n] = length
        return length

    max_length = 0
    best_start = 0

    for i in range(1, limit):
        length = get_length(i)
        if length > max_length:
            max_length = length
            best_start = i

    print(best_start)

if __name__ == "__main__":
    solve()