"""
Project Euler - Problem 17: Number Letter Counts
Answer: 21124
Resolved on Attempt: 1 in 0.0731s
Generated by Gemini AI Agent
"""

def number_to_words_length(n):
    # Lengths of words for numbers 0 to 19
    ones = ["", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", 
            "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", 
            "seventeen", "eighteen", "nineteen"]
    
    # Lengths of words for tens multiples
    tens = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]
    
    if n == 1000:
        return len("onethousand")
    
    length = 0
    
    # Hundreds place
    if n >= 100:
        hundred_digit = n // 100
        length += len(ones[hundred_digit]) + len("hundred")
        n %= 100
        if n > 0:
            length += len("and")
            
    # Tens and Ones place
    if n >= 20:
        ten_digit = n // 10
        one_digit = n % 10
        length += len(tens[ten_digit]) + len(ones[one_digit])
    elif n > 0:
        length += len(ones[n])
        
    return length

def solve():
    total_letters = sum(number_to_words_length(i) for i in range(1, 1001))
    print(total_letters)

if __name__ == "__main__":
    solve()