"""
Project Euler - Problem 15: Lattice Paths
Answer: 137846528820
Resolved on Attempt: 1 in 0.0806s
Generated by Gemini AI Agent
"""

import math

def solve():
    # For an n x n grid, a path to the bottom-right corner requires 
    # n moves to the right and n moves down, for a total of 2n moves.
    # The number of unique paths is the number of ways to choose 
    # n right-moves out of 2n total moves, which is given by the binomial coefficient:
    # C(2n, n) = (2n)! / (n! * n!)
    
    n = 20
    answer = math.comb(2 * n, n)
    print(answer)

if __name__ == "__main__":
    solve()