"""
Project Euler - Problem 19: Counting Sundays
Answer: 171
Resolved on Attempt: 1 in 0.0577s
Generated by Gemini AI Agent
"""

def solve():
    def is_leap(year):
        if year % 400 == 0:
            return True
        if year % 100 == 0:
            return False
        if year % 4 == 0:
            return True
        return False

    def days_in_month(year, month):
        if month in {9, 4, 6, 11}:
            return 30
        elif month == 2:
            return 29 if is_leap(year) else 28
        else:
            return 31

    # 1 Jan 1900 was a Monday.
    # Let's represent days of the week as 0=Monday, 1=Tuesday, ..., 6=Sunday.
    current_day_of_week = 0  # 1 Jan 1900 is Monday

    # Simulate year 1900 to get the correct day of the week for 1 Jan 1901
    for month in range(1, 13):
        current_day_of_week = (current_day_of_week + days_in_month(1900, month)) % 7

    sunday_count = 0

    # Now simulate the 20th century: 1 Jan 1901 to 31 Dec 2000
    for year in range(1901, 2001):
        for month in range(1, 13):
            # Check if the 1st of the month is a Sunday (day 6)
            if current_day_of_week == 6:
                sunday_count += 1
            # Advance the day of the week by the number of days in the current month
            current_day_of_week = (current_day_of_week + days_in_month(year, month)) % 7

    print(sunday_count)

if __name__ == '__main__':
    solve()